// Code generated by "stringer -type ObjectType -linecomment"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntegerObjectType-0]
	_ = x[StringObjectType-1]
	_ = x[ArrayObjectType-2]
	_ = x[BooleanObjectType-3]
	_ = x[NullObjectType-4]
	_ = x[ReturnValueObjectType-5]
	_ = x[ErrorObjectType-6]
	_ = x[FunctionObjectType-7]
	_ = x[BuiltinObjectType-8]
}

const _ObjectType_name = "INTEGERSTRINGARRAYBOOLEANNULLRETURN_VALUEERRORFUNCTIONBUILTIN"

var _ObjectType_index = [...]uint8{0, 7, 13, 18, 25, 29, 41, 46, 54, 61}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
