// Code generated by "stringer -type ObjectType -linecomment"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntegerObjectType-0]
	_ = x[StringObjectType-1]
	_ = x[BooleanObjectType-2]
	_ = x[NullObjectType-3]
	_ = x[ReturnValueObjectType-4]
	_ = x[ErrorObjectType-5]
	_ = x[FunctionObjectType-6]
	_ = x[BuiltinObjectType-7]
}

const _ObjectType_name = "INTEGERSTRINGBOOLEANNULLRETURN_VALUEERRORFUNCTIONBUILTIN"

var _ObjectType_index = [...]uint8{0, 7, 13, 20, 24, 36, 41, 49, 56}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
