// Code generated by "stringer -type=IOType -linecomment"; DO NOT EDIT.

package teio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IOTypeRead-0]
	_ = x[IOTypeWrite-1]
}

const _IOType_name = "readwrite"

var _IOType_index = [...]uint8{0, 4, 9}

func (i IOType) String() string {
	if i < 0 || i >= IOType(len(_IOType_index)-1) {
		return "IOType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IOType_name[_IOType_index[i]:_IOType_index[i+1]]
}
