name: monkey
on:
  push:
    branches:
      - 'master'
    paths:
      - 'syakyo/monkey/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: run test
        run: |
          make -C syakyo/monkey test
